import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import type { ScopingSession } from "../types";
import { saveAs } from "file-saver";

function formatDate(date?: string): string {
  if (!date) {
    return "Not available";
  }

  return new Date(date).toLocaleString();
}

function safeJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

export async function downloadDocxFile(
  session: ScopingSession
): Promise<void> {
  const markdown = buildMarkdownExport(session);

  const lines = markdown.split("\n");

  const paragraphs = lines.map((line) => {
    if (line.startsWith("# ")) {
      return new Paragraph({
        text: line.replace("# ", ""),
        heading: HeadingLevel.TITLE,
      });
    }

    if (line.startsWith("## ")) {
      return new Paragraph({
        text: line.replace("## ", ""),
        heading: HeadingLevel.HEADING_1,
      });
    }

    if (line.startsWith("### ")) {
      return new Paragraph({
        text: line.replace("### ", ""),
        heading: HeadingLevel.HEADING_2,
      });
    }

    if (line.startsWith("- ")) {
      return new Paragraph({
        text: line.replace("- ", ""),
        bullet: {
          level: 0,
        },
      });
    }

    if (line.startsWith("> ")) {
      return new Paragraph({
        children: [
          new TextRun({
            text: line.replace("> ", ""),
            italics: true,
          }),
        ],
      });
    }

    return new Paragraph({
      text: line.replace(/\*\*/g, ""),
    });
  });

  const document = new Document({
    sections: [
      {
        properties: {},
        children: paragraphs,
      },
    ],
  });

  const buffer = await Packer.toBlob(document);

  const filename = `${session.name
    .replace(/[^a-z0-9]/gi, "-")
    .toLowerCase()}-scope.docx`;

  saveAs(buffer, filename);
}

export function downloadMarkdownFile(
  session: ScopingSession
): void {
  const markdown = buildMarkdownExport(session);

  const blob = new Blob([markdown], {
    type: "text/markdown;charset=utf-8",
  });

  const filename = `${session.name
    .replace(/[^a-z0-9]/gi, "-")
    .toLowerCase()}-scope.md`;

  saveAs(blob, filename);
}

export function buildMarkdownExport(
  session: ScopingSession
): string {
  const scopeModel = session.scopeModel;
  const functionalScope = session.functionalScope;
  const architecture = session.architectureModel;
  const dataAI = session.dataAISolution;
  const estimation = session.estimationModel;
  const qualityGate = session.qualityGate;

  const requirements = scopeModel?.requirements ?? [];
  const assumptions = scopeModel?.assumptions ?? [];
  const questions = scopeModel?.clarificationQuestions ?? [];

  let markdown = "";

  markdown += `# Solution Scoping Package\n\n`;

  markdown += `> **Important:** This document was generated by ScopeAI. `;
  markdown += `AI-generated content, assumptions, estimates, and recommendations `;
  markdown += `must be reviewed and validated by qualified human stakeholders `;
  markdown += `before being used for contractual, financial, architectural, `;
  markdown += `or delivery decisions.\n\n`;

  markdown += `## 1. Executive Summary\n\n`;
  markdown += `**Customer:** ${session.customerName}\n\n`;
  markdown += `**Opportunity:** ${session.name}\n\n`;
  markdown += `**Preferred Cloud:** ${session.preferredCloud}\n\n`;
  markdown += `**Generated:** ${formatDate(new Date().toISOString())}\n\n`;

  markdown += `## 2. Customer Context\n\n`;
  markdown += `**Industry:** ${
    session.customerContext.industry || "Not specified"
  }\n\n`;

  markdown += `${
    session.customerContext.description ||
    "No customer description was provided."
  }\n\n`;

  markdown += `## 3. Original Requirements\n\n`;
  markdown += "```text\n";
  markdown += session.rawRequirements;
  markdown += "\n```\n\n";

  markdown += `## 4. Structured Requirements\n\n`;

  if (requirements.length === 0) {
    markdown += `No structured requirements have been generated.\n\n`;
  } else {
    markdown += `| ID | Type | Description | Priority | Origin |\n`;
    markdown += `|---|---|---|---|---|\n`;

    for (const requirement of requirements) {
      markdown += `| ${requirement.id} | `;
      markdown += `${requirement.type} | `;
      markdown += `${requirement.description.replace(/\|/g, "\\|")} | `;
      markdown += `${requirement.priority} | `;
      markdown += `${requirement.origin} |\n`;
    }

    markdown += "\n";
  }

  markdown += `## 5. Assumptions\n\n`;

  if (assumptions.length === 0) {
    markdown += `No assumptions recorded.\n\n`;
  } else {
    for (const assumption of assumptions) {
      markdown += `- **${assumption.id}:** `;
      markdown += `${assumption.description}\n`;
    }

    markdown += "\n";
  }

  markdown += `## 6. Clarification Questions\n\n`;

  if (questions.length === 0) {
    markdown += `No clarification questions recorded.\n\n`;
  } else {
    for (const question of questions) {
      markdown += `- **${question.id}:** ${question.question} `;
      markdown += `— Status: ${question.status}\n`;
    }

    markdown += "\n";
  }

  markdown += `## 7. Functional Scope\n\n`;

  if (!functionalScope) {
    markdown += `Functional scope has not been generated.\n\n`;
  } else {
    markdown += `### Capabilities\n\n`;

    for (const capability of functionalScope.capabilities) {
      markdown += `- **${capability.id}: ${capability.name}** — `;
      markdown += `${capability.description}\n`;
    }

    markdown += `\n### Modules\n\n`;

    for (const module of functionalScope.modules) {
      markdown += `- **${module.id}: ${module.name}** — `;
      markdown += `${module.description}\n`;
    }

    markdown += `\n### Workstreams\n\n`;

    for (const workstream of functionalScope.workstreams) {
      markdown += `- **${workstream.id}: ${workstream.name}** — `;
      markdown += `${workstream.description}\n`;
    }

    markdown += "\n";
  }

  markdown += `## 8. Architecture\n\n`;

  if (!architecture) {
    markdown += `Architecture has not been generated.\n\n`;
  } else {
    markdown += `**Cloud Platform:** ${architecture.cloudPlatform}\n\n`;

    markdown += `### Components\n\n`;

    for (const component of architecture.components) {
      markdown += `#### ${component.id}: ${component.name}\n\n`;
      markdown += `- **Type:** ${component.type}\n`;
      markdown += `- **Cloud Service:** ${component.cloudService}\n`;
      markdown += `- **Description:** ${component.description}\n`;
      markdown += `- **Rationale:** ${component.rationale}\n`;
      markdown += `- **Requirement IDs:** ${
        component.requirementIds.join(", ") || "None"
      }\n\n`;
    }

    markdown += `### Architecture Assumptions\n\n`;

    for (const assumption of architecture.assumptions) {
      markdown += `- ${assumption}\n`;
    }

    markdown += "\n";
  }

  markdown += `## 9. Data and AI Strategy\n\n`;

  if (!dataAI) {
    markdown += `Data and AI analysis has not been generated.\n\n`;
  } else {
    markdown += `### Data Entities\n\n`;

    for (const entity of dataAI.dataEntities) {
      markdown += `- **${entity.name}** — ${entity.description}\n`;
    }

    markdown += `\n### Integrations\n\n`;

    for (const integration of dataAI.integrations) {
      markdown += `- **${integration.name}** — `;
      markdown += `${integration.description}\n`;
    }

    markdown += `\n### AI Decision Points\n\n`;

    for (const decision of dataAI.aiDecisionPoints) {
      markdown += `- **${decision.title}** — `;
      markdown += `${decision.description}\n`;
      markdown += `  - Decision Mode: ${decision.decisionMode}\n`;
    }

    markdown += "\n";
  }

  markdown += `## 10. Estimation and Timeline\n\n`;

  if (!estimation) {
    markdown += `Estimation has not been generated.\n\n`;
  } else {
    markdown += `- **Currency:** ${estimation.currency}\n`;
    markdown += `- **Total Hours:** ${estimation.totalHours}\n`;
    markdown += `- **Estimated Duration:** `;
    markdown += `${estimation.estimatedDurationWeeks} weeks\n`;
    markdown += `- **Subtotal:** ${estimation.subtotal}\n`;
    markdown += `- **Contingency:** `;
    markdown += `${estimation.contingencyPercentage}%\n`;
    markdown += `- **Contingency Amount:** `;
    markdown += `${estimation.contingencyAmount}\n`;
    markdown += `- **Total Estimate:** ${estimation.totalEstimate}\n`;
    markdown += `- **Confidence:** ${estimation.confidence}\n\n`;

    markdown += `### Timeline\n\n`;

    for (const phase of estimation.timelinePhases) {
      markdown += `- **${phase.name}** — `;
      markdown += `${phase.durationWeeks} weeks: `;
      markdown += `${phase.description}\n`;
    }

    markdown += "\n";
  }

  markdown += `## 11. Quality Gate\n\n`;

  if (!qualityGate) {
    markdown += `The quality gate has not been executed.\n\n`;
  } else {
    markdown += `- **Overall Status:** ${qualityGate.summary.overallStatus}\n`;
    markdown += `- **Total Checks:** ${qualityGate.summary.totalChecks}\n`;
    markdown += `- **Passed:** ${qualityGate.summary.passedChecks}\n`;
    markdown += `- **Failed:** ${qualityGate.summary.failedChecks}\n`;
    markdown += `- **Warnings:** ${qualityGate.summary.warningChecks}\n\n`;

    markdown += `### Quality Checks\n\n`;

    for (const result of qualityGate.results) {
      markdown += `- **${result.title}** — `;
      markdown += `${result.status}: ${result.description}\n`;
    }

    markdown += "\n";
  }

  markdown += `## 12. Change History\n\n`;

  if (!session.changeHistory || session.changeHistory.length === 0) {
    markdown += `No changes have been recorded.\n\n`;
  } else {
    for (const change of session.changeHistory) {
      markdown += `- **${change.title}** `;
      markdown += `(${change.changeType}) — `;
      markdown += `${change.description}\n`;
    }

    markdown += "\n";
  }

  markdown += `## 13. Export Metadata\n\n`;
  markdown += `- **Session ID:** ${session.id}\n`;
  markdown += `- **Last Updated:** ${formatDate(session.updatedAt)}\n`;
  markdown += `- **Analysis Status:** ${session.analysisStatus}\n\n`;

  markdown += `---\n\n`;
  markdown += `Generated by **ScopeAI** — Intelligent, traceable solution scoping.\n`;

  return markdown;
}